import { Controller, Post, Get, Param, UseGuards, Req, Body, UseInterceptors, UploadedFile, Query } from '@nestjs/common';
import { ContractsService } from './contracts.service';
import { JwtAuthGuard } from '../auth/jwt.strategy';
import { ApiBody, ApiOperation, ApiTags, ApiBearerAuth, ApiResponse, ApiConsumes, ApiQuery } from '@nestjs/swagger';
import { FileInterceptor } from '@nestjs/platform-express';
import { SignContractDto } from './dto/sign-contract.dto';
import { CreateContractPackageDto } from './dto/create-contract-package.dto';
import { CreateContractInfoDto } from './dto/create-contract-info.dto';
import { RolesGuard } from '../../common/guards/roles.guard';
import { Roles } from '../../common/decorators/roles.decorator';
import { AccountRole } from '../accounts/enums/account-role.enum';

@ApiTags('Contracts')
@Controller('contracts')
export class ContractsController {
    constructor(private readonly contractsService: ContractsService) { }


    @Get('packages/:id')
    @UseGuards(JwtAuthGuard, RolesGuard)
    @Roles(AccountRole.ADMIN, AccountRole.CLINIC_MANAGER, AccountRole.DOCTOR, AccountRole.CLINIC_STAFF)
    @ApiBearerAuth('JWT-auth')
    @ApiOperation({ summary: 'Get contract package by ID' })
    async getPackageById(@Param('id') id: string) {
        return this.contractsService.getPackageById(id);
    }

    @Get('packages')
    @UseGuards(JwtAuthGuard, RolesGuard)
    @Roles(AccountRole.ADMIN, AccountRole.CLINIC_MANAGER, AccountRole.DOCTOR, AccountRole.CLINIC_STAFF)
    @ApiBearerAuth('JWT-auth')
    @ApiOperation({ summary: 'Get all contract packages for the logged-in clinic' })
    @ApiQuery({ name: 'employeeName', required: false, description: 'Search by employee name' })
    @ApiQuery({ name: 'page', required: false, type: Number })
    @ApiQuery({ name: 'limit', required: false, type: Number })
    async getPackages(
        @Req() req,
        @Query('employeeName') employeeName?: string,
        @Query('page') page: number = 1,
        @Query('limit') limit: number = 10,
    ) {
        const clinicId = req.user._id;
        return this.contractsService.getPackagesByClinic(clinicId, employeeName, page, limit);
    }

    @Post('packages')
    @UseGuards(JwtAuthGuard, RolesGuard)
    @Roles(AccountRole.ADMIN, AccountRole.CLINIC_MANAGER)
    @ApiBearerAuth('JWT-auth')
    @ApiOperation({ summary: 'Create a new contract package (Step 1)' })
    @ApiResponse({ status: 201, description: 'Contract package created successfully' })
    async createPackage(@Body() dto: CreateContractPackageDto, @Req() req) {
        const clinicId = req.user._id;
        return this.contractsService.createPackage(dto, clinicId);
    }

    @Post('packages/:id/info')
    @UseGuards(JwtAuthGuard, RolesGuard)
    @Roles(AccountRole.ADMIN, AccountRole.CLINIC_MANAGER, AccountRole.DOCTOR, AccountRole.CLINIC_STAFF)
    @ApiBearerAuth('JWT-auth')
    @ApiOperation({ summary: 'Create contract terms/information (Step 2)' })
    @ApiResponse({ status: 201, description: 'Contract information created successfully' })
    async createContractInfo(@Param('id') id: string, @Body() dto: CreateContractInfoDto) {
        return this.contractsService.createContractInfo(id, dto);
    }

    @Post(':id/sign')
    @UseGuards(JwtAuthGuard)
    @ApiBearerAuth('JWT-auth')
    @ApiOperation({ summary: 'Sign a contract with digital signature' })
    @ApiBody({ type: SignContractDto })
    async signContract(@Param('id') id: string, @Body() dto: SignContractDto, @Req() req) {
        return this.contractsService.signContract(id, req.user._id);
    }

    @Get(':id/verify')
    async verifyContract(@Param('id') id: string) {
        return this.contractsService.verifyContract(id);
    }

    @Post(':id/upload')
    @UseInterceptors(FileInterceptor('file', {
        limits: { fileSize: 50 * 1024 * 1024 } // Limit 50MB
    }))
    @ApiOperation({ summary: 'Upload contract PDF file (generated by Frontend)' })
    @ApiConsumes('multipart/form-data')
    @ApiBody({
        schema: {
            type: 'object',
            properties: {
                file: {
                    type: 'string',
                    format: 'binary',
                },
            },
        },
    })
    async uploadContractFile(
        @Param('id') id: string,
        @UploadedFile() file: any
    ) {
        return this.contractsService.uploadContractFile(id, file);
    }
}
