import { Controller, Post, Get, Param, UseGuards, Req, Body, UseInterceptors, UploadedFile } from '@nestjs/common';
import { ContractsService } from './contracts.service';
import { JwtAuthGuard } from '../auth/jwt.strategy';
import { ApiBody, ApiOperation, ApiTags, ApiBearerAuth, ApiResponse, ApiConsumes } from '@nestjs/swagger';
import { FileInterceptor } from '@nestjs/platform-express';
import { SignContractDto } from './dto/sign-contract.dto';
import { CreateContractPackageDto } from './dto/create-contract-package.dto';
import { CreateContractInfoDto } from './dto/create-contract-info.dto';
import { RolesGuard } from '../../common/guards/roles.guard';
import { Roles } from '../../common/decorators/roles.decorator';
import { AccountRole } from '../accounts/enums/account-role.enum';

@ApiTags('Contracts')
@Controller('contracts')
export class ContractsController {
    constructor(private readonly contractsService: ContractsService) { }

    @Post('packages')
    // @UseGuards(JwtAuthGuard, RolesGuard)
    // @Roles(AccountRole.ADMIN, AccountRole.CLINIC_MANAGER)
    // @ApiBearerAuth('JWT-auth')
    @ApiOperation({ summary: 'Create a new contract package (Step 1)' })
    @ApiResponse({ status: 201, description: 'Contract package created successfully' })
    async createPackage(@Body() dto: CreateContractPackageDto, @Req() req) {
        // Assume Clinic ID is the user's ID (for Clinic Manager)
        // const clinicId = req.user.id; 
        const clinicId = dto.clinicId; // For manual testing as requested
        return this.contractsService.createPackage(dto, clinicId);
    }

    @Post('packages/:id/info')
    // @UseGuards(JwtAuthGuard, RolesGuard)
    // @Roles(AccountRole.ADMIN, AccountRole.CLINIC_MANAGER)
    // @ApiBearerAuth('JWT-auth')
    @ApiOperation({ summary: 'Create contract terms/information (Step 2)' })
    @ApiResponse({ status: 201, description: 'Contract information created successfully' })
    async createContractInfo(@Param('id') id: string, @Body() dto: CreateContractInfoDto) {
        return this.contractsService.createContractInfo(id, dto);
    }

    @Post(':id/sign')
    @ApiOperation({ summary: 'Sign a contract with digital signature' })
    @ApiBody({ type: SignContractDto })
    async signContract(@Param('id') id: string, @Body() dto: SignContractDto) {
        return this.contractsService.signContract(id, dto.userId);
    }

    @Get(':id/verify')
    async verifyContract(@Param('id') id: string) {
        return this.contractsService.verifyContract(id);
    }

    @Post(':id/upload')
    @UseInterceptors(FileInterceptor('file'))
    @ApiOperation({ summary: 'Upload contract PDF file (generated by Frontend)' })
    @ApiConsumes('multipart/form-data')
    @ApiBody({
        schema: {
            type: 'object',
            properties: {
                file: {
                    type: 'string',
                    format: 'binary',
                },
            },
        },
    })
    async uploadContractFile(
        @Param('id') id: string,
        @UploadedFile() file: any
    ) {
        return this.contractsService.uploadContractFile(id, file);
    }
}
