import { IsEmail, IsNotEmpty, IsOptional, IsString, IsDateString } from 'class-validator';
import { ApiProperty } from '@nestjs/swagger';

export class SendAccountCredentialsDto {
  @ApiProperty({
    description: 'Email address to send the credentials to',
    example: 'user@example.com',
  })
  @IsEmail({}, { message: 'Invalid email format' })
  @IsNotEmpty({ message: 'Target email is required' })
  email: string;

  @ApiProperty({
    description: 'Patient full name',
    example: 'John Doe',
  })
  @IsString()
  @IsNotEmpty({ message: 'Full name is required' })
  fullName: string;

  @ApiProperty({
    description: 'Login username (usually the email)',
    example: 'user@example.com',
  })
  @IsString()
  @IsNotEmpty({ message: 'Username is required' })
  username: string;

  @ApiProperty({
    description: 'Temporary password generated by the system',
    example: 'Abc123xyz!',
  })
  @IsString()
  @IsNotEmpty({ message: 'Temporary password is required' })
  temporaryPassword: string;

  @ApiProperty({
    description: 'Patient phone number',
    example: '0912345678',
    required: false,
  })
  @IsOptional()
  @IsString()
  phone?: string;

  @ApiProperty({
    description: 'Patient date of birth',
    example: '1990-01-01',
    required: false,
  })
  @IsOptional()
  @IsDateString()
  dateOfBirth?: string;
}
