export enum ContractStatus {
  OLD = 'OLD',
  CURRENT = 'CURRENT',
  PENDING_SIGNATURE = 'PENDING_SIGNATURE',
  PENDING_MANAGER_SIGNATURE = 'PENDING_MANAGER_SIGNATURE',
  REJECTED = 'REJECTED',
  DRAFT = 'DRAFT',
  CANCELLED = 'CANCEL_CONTRACT',
}
