import { ApiProperty } from '@nestjs/swagger';
import { Gender } from '../enums';

/**
 * Patient Data DTO
 *
 * Detailed patient information returned when patient is found in the system
 */
export class PatientDataDto {
  @ApiProperty({
    description: 'Patient account ID',
    example: '123e4567-e89b-12d3-a456-426614174000',
  })
  accountId: string;

  @ApiProperty({
    description: 'Patient email address',
    example: 'nguyenvana@gmail.com',
  })
  email: string;

  @ApiProperty({
    description: 'Patient phone number',
    example: '0912345678',
  })
  phone: string;

  @ApiProperty({
    description: 'Patient full name',
    example: 'John Doe',
  })
  fullName: string;

  @ApiProperty({
    description: 'Date of birth',
    example: '1990-01-15',
    required: false,
  })
  dateOfBirth?: string;

  @ApiProperty({
    description: 'Patient gender',
    enum: Gender,
    example: Gender.MALE,
    required: false,
  })
  gender?: Gender;

  @ApiProperty({
    description: 'Patient address',
    example: '123 Main Street, District 1, Ho Chi Minh City',
    required: false,
  })
  address?: string;

  @ApiProperty({
    description: 'Account creation timestamp',
    example: '2025-12-01T10:30:00Z',
  })
  createdAt: string;

  @ApiProperty({
    description: 'Indicates if patient has a temporary email (generated by system)',
    example: false,
  })
  isTempEmail: boolean;
}

/**
 * Patient Search Response DTO
 *
 * Response for patient search operation by clinic staff
 * Returns patient data if found, or suggestion to create new account
 */
export class PatientSearchResponseDto {
  @ApiProperty({
    description: 'Indicates if patient was found in the system',
    example: true,
  })
  found: boolean;

  @ApiProperty({
    description: 'Patient details if found',
    type: PatientDataDto,
    required: false,
  })
  patient?: PatientDataDto;

  @ApiProperty({
    description: 'Message when patient is not found',
    example: 'No patient found with this phone number',
    required: false,
  })
  message?: string;

  @ApiProperty({
    description: 'Suggested action when patient is not found',
    example: 'CREATE_NEW_ACCOUNT',
    required: false,
  })
  suggestedAction?: string;
}
